version: '2'

services:

  nginx:
    restart: always
    image: dockette/packagist:nginx

    volumes_from:
      - data

    depends_on:
      - php

    ports:
      # Production mode
      - 8000:8000

      # Development mode
      - 9000:9000

  php:
    restart: always
    image: dockette/packagist:php

    volumes_from:
      - data

    volumes:
      - ./config/ssh/config:/home/dfx/.ssh/config
      - ./config/ssh/id_rsa:/home/dfx/.ssh/id_rsa
      - ./config/ssh/id_rsa.pub:/home/dfx/.ssh/id_rsa.pub
      - ./config/ssh/known_hosts:/home/dfx/.ssh/known_hosts

    depends_on:
      - mysql
      - redis
      - solr

  mysql:
    restart: always
    image: mariadb:10.1

    volumes:
      - ./data/mysql:/var/lib/mysql
    
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=packagist
      - MYSQL_USER=packagist
      - MYSQL_PASSWORD=packagist

  redis:
    restart: always
    image: redis:3.2

    volumes:
      - ./data/redis:/data

  solr:
    image: solr:6.3-alpine

    volumes:
      - ./data/solr:/opt/solr/server/solr/packagist
      - ./data/solr-mycores:/opt/solr/server/solr/mycores

    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - packagist

  data:
    image: busybox

    volumes:
      - ./app:/srv
